#!/bin/bash
#

iam=$( basename $0 )

function waveforms () {

cat <<PROLOG
# \$File: //ASP/Dev/SBS/4_Controls/4_4_Equipment_Control/4_4_8_Insertion_Device_Control/sw/Feed_Forward/Feed_Forward_CommonApp/Db/gen_template.sh $
# \$Revision: 1.1.1.1 $
# \$DateTime: 2012/06/07 10:31:50 $
# Last checked in by: \$Author: saa $
#
# Description.
# This template file will define 84 (14 sectors by 6 quadrupole magnets per
# sector) waveform records, each of which will hold the feed forward
# interpolation table for one of the magnets.
#
# Formal template parameters are:
# NAME  - specifies base name, e.g. SR05FF01
# DIMS  - specifies the number of dimensions, i.e. 1, 2 or 3.
# SIZE  - required waveform size - must allow for meta data,
#         i.e. an extra 2, 3 or 4 elements.
#
# It is expected that these records will be auto saved.
#
# This template auto generated by: ${iam}
#
# Copyright (c) 2012  Australian Synchrotron
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# Licence as published by the Free Software Foundation; either
# version 2.1 of the Licence, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public Licence for more details.
#
# You should have received a copy of the GNU Lesser General Public
# Licence along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Contact details:
# andrew.starritt@synchrotron.org.au
# 800 Blackburn Road, Clayton, Victoria 3168, Australia.
#

PROLOG

for ss in $( seq -w 1 14) ; do

   for qq in 01 02 03 04 05 06 ; do 

      magnet="SR${ss:?}QPS${qq:?}"
      cat <<INLINE_DOC
record (waveform, "\$(NAME):${magnet:?}_INTERPOLATION_TABLE") {
    field (DESC, "\$(DIMS)-D interpolation table")
    field (SCAN, "Passive")
    field (PINI, "YES")
    field (FTVL, "DOUBLE")
    field (NELM, "\$(SIZE)")
    field (EGU,  "A")
    field (PREC, "3")
    field (LOPR, "-10.0")
    field (HOPR, "+10.0")
}

INLINE_DOC

   done

done

echo "# end"

}

function asubs () {

cat <<PROLOG
# \$File: //ASP/Dev/SBS/4_Controls/4_4_Equipment_Control/4_4_8_Insertion_Device_Control/sw/Feed_Forward/Feed_Forward_CommonApp/Db/gen_template.sh $
# \$Revision: 1.1.1.1 $
# \$DateTime: 2012/06/07 10:31:50 $
# Last checked in by: \$Author: saa $
#
# Description.
# This template defines the records that perform the actual interpolation
# calculations. This is achieved using a number of aSub records that use
# the Dynamic_Interpolation_Process functionality in order to calculate
# the delta current change for all 84 quadrupole magnets due to the
# position of a single insertion device.
#
# Formal template parameters are:
# NAME  - specifies base name, e.g. SR12FF01.
# DIMS  - specifies the number of dimensions, i.e. 1, 2 or 3.
#         Must be a constant, as opposed to a database link.
# SIZE  - Interpolation table size - must be consistant with contents
#         of the INPn_COORDINATE_SET waveform records.
# INP1  - first  dimension control PV variable.
# INP2  - second dimension control PV variable.
# INP3  - third  dimension control PV variable.
#         For 1-D/2-D interpolation set INP2/INP3 use constant, e.g. 0.
#
# This template auto generated by: ${iam}
#
# Copyright (c) 2012  Australian Synchrotron
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# Licence as published by the Free Software Foundation; either
# version 2.1 of the Licence, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public Licence for more details.
#
# You should have received a copy of the GNU Lesser General Public
# Licence along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Contact details:
# andrew.starritt@synchrotron.org.au
# 800 Blackburn Road, Clayton, Victoria 3168, Australia.
#

PROLOG

for inst in 1 2 3 4 5 6 7 ; do

   s1=$( expr ${inst} \* 2 - 1 )
   s2=$( expr ${inst} \* 2      )

   if [ $s1 -lt 10 ] ; then s1="0${s1}" ; fi
   if [ $s2 -lt 10 ] ; then s2="0${s2}" ; fi

   cat <<INLINE_DOC
record (aSub, "\$(NAME):INTERPOLATION_CALC_0${inst:?}") {
    field (DESC, "Interpolsation calculation ${inst:?}/7")
    field (SCAN, "Passive")

    field (INAM, "Dynamic_Interpolation_Init")
    field (SNAM, "Dynamic_Interpolation_Process")

    # Number of dimensions
    #
    field (INPA, "\$(DIMS)")
    field (FTA,  "LONG")

    # First/Last Interpolated Input/Output
    # D = 4, E = 5, ... J = 10,  ... U = 21
    # Encoded as 100*First + Last
    #
    field (INPB, "1021")        #  J .. U
    field (FTB,  "LONG")

    # Out of range input indicator
    # No separate record - just in VALA (for now).
    #
    field (FTVA, "LONG")

    # 1st input coordinates set (max 20) and coordinate.
    #
    field (INPD, "\$(NAME):INP1_COORDINATE_SET")
    field (NOD,  "22")
    field (FTD,  "DOUBLE")

    field (INPE, "\$(INP1)")
    field (FTE,  "DOUBLE")

    # 2nd input coordinates set (max 40) and coordinate.
    #
    field (INPF, "\$(NAME):INP2_COORDINATE_SET")
    field (NOF,  "42")
    field (FTF,  "DOUBLE")

    field (INPG, "\$(INP2)")
    field (FTG,  "DOUBLE")

    # 3rd input coordinates set (max 40) and coordinate.
    #
    field (INPH, "\$(NAME):INP3_COORDINATE_SET")
    field (NOH,  "42")
    field (FTH,  "DOUBLE")

    field (INPI, "\$(INP3)")
    field (FTI,  "DOUBLE")

    # Interpolation Tables and Interpolated Outputs
    # PP mode forces the record to process as it is on same IOC.
    # This mitigates need for an FLNK to each output.
    #
    # Sector ${s1:?} magnets
    #
    field (INPJ, "\$(NAME):SR${s1:?}QPS01_INTERPOLATION_TABLE")
    field (OUTJ, "\$(NAME):SR${s1:?}QPS01_TRIM_CURRENT_SP PP")
    field (NOJ,  "\$(SIZE)")
    field (FTJ,  "DOUBLE")
    field (FTVJ, "DOUBLE")

    field (INPK, "\$(NAME):SR${s1:?}QPS02_INTERPOLATION_TABLE")
    field (OUTK, "\$(NAME):SR${s1:?}QPS02_TRIM_CURRENT_SP PP")
    field (NOK,  "\$(SIZE)")
    field (FTK,  "DOUBLE")
    field (FTVK, "DOUBLE")

    field (INPL, "\$(NAME):SR${s1:?}QPS03_INTERPOLATION_TABLE")
    field (OUTL, "\$(NAME):SR${s1:?}QPS03_TRIM_CURRENT_SP PP")
    field (NOL,  "\$(SIZE)")
    field (FTL,  "DOUBLE")
    field (FTVL, "DOUBLE")

    field (INPM, "\$(NAME):SR${s1:?}QPS04_INTERPOLATION_TABLE")
    field (OUTM, "\$(NAME):SR${s1:?}QPS04_TRIM_CURRENT_SP PP")
    field (NOM,  "\$(SIZE)")
    field (FTM,  "DOUBLE")
    field (FTVM, "DOUBLE")

    field (INPN, "\$(NAME):SR${s1:?}QPS05_INTERPOLATION_TABLE")
    field (OUTN, "\$(NAME):SR${s1:?}QPS05_TRIM_CURRENT_SP PP")
    field (NON,  "\$(SIZE)")
    field (FTN,  "DOUBLE")
    field (FTVN, "DOUBLE")

    field (INPO, "\$(NAME):SR${s1:?}QPS06_INTERPOLATION_TABLE")
    field (OUTO, "\$(NAME):SR${s1:?}QPS06_TRIM_CURRENT_SP PP")
    field (NOO,  "\$(SIZE)")
    field (FTO,  "DOUBLE")
    field (FTVO, "DOUBLE")

    # Sector ${s2:?} magnets
    #
    field (INPP, "\$(NAME):SR${s2:?}QPS01_INTERPOLATION_TABLE")
    field (OUTP, "\$(NAME):SR${s2:?}QPS01_TRIM_CURRENT_SP PP")
    field (NOP,  "\$(SIZE)")
    field (FTP,  "DOUBLE")
    field (FTVP, "DOUBLE")

    field (INPQ, "\$(NAME):SR${s2:?}QPS02_INTERPOLATION_TABLE")
    field (OUTQ, "\$(NAME):SR${s2:?}QPS02_TRIM_CURRENT_SP PP")
    field (NOQ,  "\$(SIZE)")
    field (FTQ,  "DOUBLE")
    field (FTVQ, "DOUBLE")

    field (INPR, "\$(NAME):SR${s2:?}QPS03_INTERPOLATION_TABLE")
    field (OUTR, "\$(NAME):SR${s2:?}QPS03_TRIM_CURRENT_SP PP")
    field (NOR,  "\$(SIZE)")
    field (FTR,  "DOUBLE")
    field (FTVR, "DOUBLE")

    field (INPS, "\$(NAME):SR${s2:?}QPS04_INTERPOLATION_TABLE")
    field (OUTS, "\$(NAME):SR${s2:?}QPS04_TRIM_CURRENT_SP PP")
    field (NOS,  "\$(SIZE)")
    field (FTS,  "DOUBLE")
    field (FTVS, "DOUBLE")

    field (INPT, "\$(NAME):SR${s2:?}QPS05_INTERPOLATION_TABLE")
    field (OUTT, "\$(NAME):SR${s2:?}QPS05_TRIM_CURRENT_SP PP")
    field (NOT,  "\$(SIZE)")
    field (FTT,  "DOUBLE")
    field (FTVT, "DOUBLE")

    field (INPU, "\$(NAME):SR${s2:?}QPS06_INTERPOLATION_TABLE")
    field (OUTU, "\$(NAME):SR${s2:?}QPS06_TRIM_CURRENT_SP PP")
    field (NOU,  "\$(SIZE)")
    field (FTU,  "DOUBLE")
    field (FTVU, "DOUBLE")
}

INLINE_DOC

done

echo "# end"
}

if [ "${1}" == "" ] ; then
   echo "gen_template.sh: Expecting  tables or calcs"
   exit
fi

case ${1:?} in

   tables)
      waveforms
      ;;

   calcs)
      asubs
      ;;

   *)
      echo "gen_template.sh: Unknown ${1:?} - expecting tables or calcs"
      ;;

esac

# end
